<?php
$_helper = Mage::helper('ricardomartins_pagseguro');
$_ajaxSessionIdUrl = Mage::getUrl('pseguro/ajax/getSessionId', array('_secure' => true));
$_price = $this->getPrice();
$_maxInstallments = (int)Mage::getStoreConfig(
    RicardoMartins_PagSeguro_Helper_Data::XML_PATH_PAYMENT_PAGSEGURO_CC_INSTALLMENT_LIMIT
);
$_installmentsFreeOnly = (int)Mage::getStoreConfig(
    RicardoMartins_PagSeguro_Helper_Data::XML_PATH_PAYMENT_PAGSEGURO_CC_INSTALLMENT_INTEREST_FREE_ONLY
);
$_maxInstallmentNoInterest = $_helper->getMaxInstallmentsNoInterest($_price);
?>

<div id="rmpagseguro_parcelas_box">
    <p id="rmpagseguro_parcelas_loading">Carregando parcelas...</p>
    <p id="pseguro_parcelas" style="display: none;">Parcele em até <span id="installments"></span>x de R$<span id="installment_value"></span> (Total R$<span id="installment_total"></span>) com PagSeguro UOL.</p>
</div>

<script type="text/javascript">
// <![CDATA[
    document.observe("dom:loaded", function(){
        new Ajax.Request('<?php echo $_ajaxSessionIdUrl?>', {
            method: 'get',
            onSuccess: function(transport){
                PagSeguroDirectPayment.setSessionId(transport.responseJSON.session_id);
                PagSeguroDirectPayment.onSenderHashReady(updateInstallments);
            }
        });

    })
    var updateInstallments = function() {
        var maxInstallmentNoInterest = "<?php echo $_maxInstallmentNoInterest?>";
        
        PagSeguroDirectPayment.getInstallments({
            amount: <?php echo $_price?>,
            brand: 'visa',
            maxInstallmentNoInterest: maxInstallmentNoInterest,
            success: function (response) {
                var responseVisa = response.installments.visa;
                var maxInstallmentsConfig = <?php echo $_maxInstallments ?>;
                var installment = responseVisa[responseVisa.length - 1];
            <?php if($_installmentsFreeOnly): ?>
                for (i in responseVisa) {
                     if(responseVisa[i].interestFree == false){
                        installment = responseVisa[i-1];
                        break;
                     }
                }
                <?php endif;?>
                if(maxInstallmentsConfig > 0 && maxInstallmentsConfig < responseVisa.length && maxInstallmentsConfig < installment.quantity){
                    installment = responseVisa[maxInstallmentsConfig - 1];
                }
                $('installments').innerHTML = installment.quantity.toString();
                $('installment_value').innerHTML = installment.installmentAmount.toFixed(2).toString().replace('.', ',');
                $('installment_total').innerHTML = installment.totalAmount.toFixed(2).toString().replace('.', ',');
                if(installment.interestFree){
                    $('installment_total').innerHTML += ' sem juros';
                }
                $('pseguro_parcelas').setStyle({display: ''});
                $('rmpagseguro_parcelas_loading').setStyle({display: 'none'});
            }
        })
    };
// ]]>
</script>