<?php
/**
 * @package     Gamuza_Basic
 * @copyright   Copyright (c) 2016 Gamuza Technologies (http://www.gamuza.com.br/)
 * @author      Eneias Ramos de Melo <eneias@gamuza.com.br>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

/**
 * See the AUTHORS file for a list of people on the Gamuza Team.
 * See the ChangeLog files for a list of changes.
 * These files are distributed with gamuza_basic-magento at http://github.com/gamuzatech/.
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="noindex, nofollow" />
    <title><?php echo Mage::helper('adminhtml')->__('Log into Magento Admin Page') ?></title>
    <link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('reset.css') ?>" media="all" />
    <link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('boxes.css') ?>" media="all" />
    <link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('form.css') ?>" media="all" />
    <link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('override.css') ?>" media="all" />
    <link rel="icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon" />
    <link rel="shortcut icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon" />

    <link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('css/gamuza/basic/custom.css') ?>" media="all" />

    <script type="text/javascript" src="<?php echo $this->getJsUrl('prototype/prototype.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('prototype/validation.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('scriptaculous/effects.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('mage/adminhtml/form.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('mage/captcha.js') ?>"></script>

    <script type="text/javascript" src="<?php echo $this->getJsUrl ('mage/translate.js'); ?>"></script>

    <?php echo $this->helper ('core/js')->getTranslatorScript (); ?>

    <!--[if IE]> <link rel="stylesheet" href="<?php echo $this->getSkinUrl('iestyles.css') ?>" type="text/css" media="all" /> <![endif]-->
    <!--[if lt IE 7]> <link rel="stylesheet" href="<?php echo $this->getSkinUrl('below_ie7.css') ?>" type="text/css" media="all" /> <![endif]-->
    <!--[if IE 7]> <link rel="stylesheet" href="<?php echo $this->getSkinUrl('ie7.css') ?>" type="text/css" media="all" /> <![endif]-->

    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:400,300,600,700" />
</head>
<body id="page-login" onload="document.forms.loginForm.username.focus();">
    <div class="login-container">
        <div class="login-box">
            <form method="post" action="" id="loginForm" autocomplete="off">
                <div class="login-form">
                    <div class="logo" title="<?php echo Mage::helper('adminhtml')->__('Toluca Store Admin') ?>">
                        <span><?php echo Mage::helper('adminhtml')->__('Toluca Store Admin') ?></span>
                    </div>
                    <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
                    <h2><?php echo Mage::helper('adminhtml')->__('Log in to Admin Panel') ?></h2>
                    <div id="messages">
                        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
                    </div>
                    <div class="input-box"><label for="username"><?php echo Mage::helper('adminhtml')->__('User Name:') ?></label><br/>
                        <input type="text" id="username" name="login[username]" value="" class="required-entry input-text large" />
                    </div>
                    <div class="input-box"><label for="login"><?php echo Mage::helper('adminhtml')->__('Password:') ?></label><br />
                        <!-- This is a dummy hidden field to trick firefox from auto filling the password -->
                        <input type="text" class="input-text no-display" name="dummy" id="dummy" />
                        <input type="password" id="login" name="login[password]" class="required-entry input-text large" value="" />
                    </div>
                    <?php echo $this->getChildHtml('form.additional.info'); ?>
                    <div class="form-buttons">
                        <input type="submit" class="form-button ok_button large" value="<?php echo Mage::helper('adminhtml')->__('Login') ?>" title="<?php echo Mage::helper('adminhtml')->__('Login') ?>" />
                    </div>
                    <?php /*
                    <div>
                        <a class="left" href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/index/forgotpassword', array('_nosecret' => true)) ?>"><?php echo Mage::helper('adminhtml')->__('Forgot your password?') ?></a>
                    </div>
                    */ ?>
                    <div class="clear"></div>
                </div>
                <p class="legal"><?php echo $this->__('Toluca Store&trade; is a trademark of Gamuza Technologies.') ?><br/>
                <?php echo Mage::helper('adminhtml')->__('Copyright &copy; %s Gamuza Technologies. All rights reserved.', date('Y')) ?></p>
            </form>
            <script type="text/javascript">
                 var loginForm = new varienForm('loginForm');
            </script>
        </div>
    </div>
</body>
</html>

