<?php
/**
 * @package     Gamuza_PagCripto
 * @copyright   Copyright (c) 2022 Gamuza Technologies (http://www.gamuza.com.br/)
 * @author      Eneias Ramos de Melo <eneias@gamuza.com.br>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

/**
 * See the AUTHORS file for a list of people on the Gamuza Team.
 * See the ChangeLog files for a list of changes.
 * These files are distributed with gamuza_pagcripto-magento at http://github.com/gamuzatech/.
 */
?>
<?php $_code=$this->getMethodCode() ?>
<style>
#payment_form_gamuza_pagcripto_payment .form-item  { display: inline-block; padding: 20px; }
#payment_form_gamuza_pagcripto_payment .form-logo  { display: block; padding-bottom: 30px; }
#payment_form_gamuza_pagcripto_payment .form-price { display: block; padding-bottom: 20px; }
</style>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Crypto Currency Types') ?></label>
        <div class="input-box">
            <?php $_ccType = $this->getInfoData('cc_type') ?>
            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                <div class="form-item">
                    <p><label for="<?php echo $_code . '_' . $_typeCode ?>_cc_type">
                        <img src="<?php echo $this->getSkinUrl($_code . '-' . $_typeCode) ?>-logo.png" alt="<?php echo $_typeName ?>" title="<?php echo $_typeName; ?>" width="64" />
                    </label></p>
                    <p><input id="<?php echo $_code . '_' . $_typeCode ?>_cc_type" name="payment[cc_type]" title="<?php echo $_typeName ?>"
                        type="radio" value="<?php echo $_typeCode ?>" <?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>
                        class="validate-one-required-by-name">
                    <label for="<?php echo $_code . '_' . $_typeCode ?>_cc_type"><?php echo $_typeName ?></label></p>
                </div>
            <?php endforeach ?>
        </div>
    </li>
    <?php if ($this->getInstructions()): ?>
    <li>
        <div class="<?php echo $_code; ?>-instructions-content agreement-content">
            <?php echo nl2br($this->getInstructions()) ?>
        </div>
    </li>
    <?php endif; ?>
    <?php echo $this->getChildHtml() ?>
</ul>

