<?php
/***************************************************************************
 Extension Name  : Magento Responsive Banner Slider with Lazy Load Extension
 Extension URL   : http://www.magebees.com/magento-responsive-banner-slider-with-lazy-load-extension.html
 Copyright    : Copyright (c) 2016 MageBees, http://www.magebees.com
 Support Email   : support@magebees.com 
 ***************************************************************************/
?> 
<?php if(count($this->getGroupData()) > 1) { ?>
<?php $url = Mage::helper('adminhtml')->getUrl('adminhtml/slider/index'); ?>
<?php $group_id = $this->getRequest()->getParam('group'); ?>
<p class="switcher"><label for="store_switcher"><?php echo $this->__('Choose Slider Group:') ?></label>
    <select name="store_switcher" id="store_switcher" onchange="return switchStore(this);">
         <option value="0"><?php echo $this->__('Show All Slider Group'); ?></option>
        <?php foreach($this->getGroupData() as $key => $value) { 
            if($group_id == $key){
            ?>
                <option value="<?php echo $key; ?>" selected><?php echo $value; ?></option>
            <?php }else{?>
                <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
            <?php }    ?>
        <?php }?>
    </select>
</p>
<script type="text/javascript">
    function switchStore(obj) {
        var storeParam = obj.value ? 'group/' + obj.value + '/' : '';
        if (obj.switchParams) {
            storeParam += obj.switchParams;
        }
        setLocation('<?php echo $url ?>' + storeParam);
    }
</script> 
<?php }?>