<?php
/**
 * @package     Gamuza_Mobile
 * @copyright   Copyright (c) 2023 Gamuza Technologies (http://www.gamuza.com.br/)
 * @author      Eneias Ramos de Melo <eneias@gamuza.com.br>
 */
?>

<?php
$_order = $this->getOrder();

echo Mage::helper('sales')->__('Order: %s-%s', $_order->getRealOrderId(), $_order->getProtectCode()) . PHP_EOL;
echo Mage::helper('core')->formatDate($_order->getCreatedAtDate(), 'medium', true) . PHP_EOL;
echo str_repeat('-', 30) . PHP_EOL;

$address = $_order->getShippingAddress() ? $_order->getShippingAddress() : $_order->getBillingAddress();

echo Mage::helper ('customer')->__('Customer: %s', $address->getFirstname()) . PHP_EOL;
echo $address->getCellphone() . PHP_EOL;
echo sprintf('%s %s', $address->getStreet1(), $address->getStreet2()) . PHP_EOL;
if ($address->getStreet3()) echo $address->getStreet3() . PHP_EOL;
echo $address->getStreet4() . PHP_EOL;
echo sprintf('%s %s %s', $address->getCity(), $address->getRegionCode(), $address->getCountryId()) . PHP_EOL;
echo $address->getPostcode() . PHP_EOL;
echo str_repeat('-', 30) . PHP_EOL;

echo Mage::helper('sales')->__('Total Items Qty: %s', intval($_order->getTotalQtyOrdered())) . PHP_EOL;
echo str_repeat('-', 30) . PHP_EOL;

foreach ($_order->getAllItems() as $item)
{
    echo Mage::helper ('catalog')->__('SKU: %s', $item->getSku()) . PHP_EOL;
    echo $item->getName() . PHP_EOL;

    $productOptions = $item->getProductOptions();

    foreach ($productOptions ['options'] as $option)
    {
        echo sprintf('%s: %s', $option ['label'], $option ['value']) . PHP_EOL;
    }

    foreach ($productOptions ['additional_options'] as $option)
    {
        echo sprintf('%s: %s', $option ['label'], $option ['value']) . PHP_EOL;
    }

    if ($item->getParentItemId ())
    {
        echo str_repeat('-', 30) . PHP_EOL;

        continue; // skip
    }

    $price = Mage::helper('core')->currency($item->getPrice(), true, false);
    $qty   = intval($item->getQtyOrdered());

    echo Mage::helper('sales')->__('Price: %s', $price) . PHP_EOL;
    echo Mage::helper('sales')->__('Qty: %s', $qty) . PHP_EOL;

    $rowTotal = Mage::helper('core')->currency($item->getBaseRowTotal(), true, false);

    echo Mage::helper('sales')->__('Total: %s', $rowTotal) . PHP_EOL;

    echo str_repeat('-', 30) . PHP_EOL;
}

$subtotal = Mage::helper('core')->currency($_order->getBaseSubtotal(), true, false);
$shipping = Mage::helper('core')->currency($_order->getBaseShippingAmount(), true, false);
$total    = Mage::helper('core')->currency($_order->getBaseGrandTotal(), true, false);

echo Mage::helper('sales')->__('Subtotal: %s', $subtotal) . PHP_EOL;
echo Mage::helper('sales')->__('Shipping: %s', $shipping) . PHP_EOL;
echo Mage::helper('sales')->__('Grand Total: %s', $total) . PHP_EOL;
echo str_repeat('-', 30) . PHP_EOL;

echo $_order->getShippingDescription() . PHP_EOL;
echo str_repeat('-', 30) . PHP_EOL;

echo Mage::helper('payment')->getInfoBlock($_order->getPayment())->toHtml() . PHP_EOL;
echo str_repeat('-', 30) . PHP_EOL;

echo Mage::getStoreConfig('general/store_information/name',    $_order->getStoreId()) . PHP_EOL;
echo Mage::getStoreConfig('general/store_information/address', $_order->getStoreId()) . PHP_EOL;
echo Mage::getStoreConfig('general/store_information/phone',   $_order->getStoreId()) . PHP_EOL;
echo Mage::getModel('core/date')->date('d/m/Y H:i:s') . PHP_EOL;

