<?php
/**
 * @package     Gamuza_Mobile
 * @copyright   Copyright (c) 2023 Gamuza Technologies (http://www.gamuza.com.br/)
 * @author      Eneias Ramos de Melo <eneias@gamuza.com.br>
 */
?>

<?php
$_order = $this->getOrder();

echo $this->getLineSeparator(Mage::helper('basic')->__('Order')) . PHP_EOL;

echo sprintf('%s %s', $this->getOrderNumber(), $this->getOrderDatetime()) . PHP_EOL;

$address = $_order->getShippingAddress() ? $_order->getShippingAddress() : $_order->getBillingAddress();

echo $this->getLineSeparator(Mage::helper('basic')->__('Customer')) . PHP_EOL;

echo sprintf('%s %s', $address->getFirstname(), $address->getCellphone()) . PHP_EOL;
echo sprintf('%s %s %s', $address->getStreet1(), $address->getStreet2(), $address->getStreet3()) . PHP_EOL;
echo sprintf('%s %s', $address->getStreet4(), $address->getPostcode()) . PHP_EOL;
echo sprintf('%s %s %s', $address->getCity(), $address->getRegionCode(), $address->getCountryId()) . PHP_EOL;
echo $this->getLineSeparator() . PHP_EOL;

echo Mage::helper('sales')->__('Total Items Qty: %s', intval($_order->getTotalQtyOrdered())) . PHP_EOL;

foreach ($_order->getAllItems() as $item)
{
    echo $this->getLineSeparator($item->getSku()).PHP_EOL;
    echo $item->getName() . PHP_EOL;

    $productOptions = $item->getProductOptions();

    foreach ($productOptions ['options'] as $option)
    {
        echo sprintf('%s: %s', $option ['label'], $option ['value']) . PHP_EOL;
    }

    foreach ($productOptions ['additional_options'] as $option)
    {
        echo sprintf('%s: %s', $option ['label'], $option ['value']) . PHP_EOL;
    }

    if ($item->getParentItemId ())
    {
        continue; // skip
    }

    $price = Mage::helper('core')->currency($item->getPrice(), true, false);
    $qty = floatval($item->getQtyOrdered());
    $rowTotal = Mage::helper('core')->currency($item->getBaseRowTotal(), true, false);

    echo Mage::helper('basic')->__('Price: %s Qty: %s Total: %s', $price, $qty, $rowTotal) . PHP_EOL;
}

echo $this->getLineSeparator() . PHP_EOL;

$subtotal = Mage::helper('core')->currency($_order->getBaseSubtotal(), true, false);
$shipping = Mage::helper('core')->currency($_order->getBaseShippingAmount(), true, false);
$total    = Mage::helper('core')->currency($_order->getBaseGrandTotal(), true, false);

echo Mage::helper('sales')->__('Subtotal: %s Shipping: %s', $subtotal, $shipping) . PHP_EOL;
echo Mage::helper('sales')->__('Grand Total: %s', $total) . PHP_EOL;
echo $this->getLineSeparator() . PHP_EOL;

echo $_order->getShippingDescription() . PHP_EOL;

$_paymentMethod = $_order->getPayment()->getMethodInstance();

if ($_paymentMethod)
{
    echo $_paymentMethod->getTitle() . PHP_EOL;

    $_paymentInfo = Mage::helper('payment')->getInfoBlock($_order->getPayment());

    if ($_paymentInfo)
    {
        foreach ($_paymentInfo->getSpecificInformation() as $id => $value)
        {
            echo sprintf('%s: %s', $id, $value) . PHP_EOL;
        }
    }
}
else
{
    echo Mage::helper('adminhtml')->__('Payment method is not available.') . PHP_EOL;
}

echo $this->getLineSeparator() . PHP_EOL;

$storeName  = Mage::getStoreConfig('general/store_information/name',  $_order->getStoreId());
$storePhone = Mage::getStoreConfig('general/store_information/phone', $_order->getStoreId());

echo sprintf('%s %s', $storeName, $storePhone) . PHP_EOL;

echo sprintf('Toluca Store APP %s', Mage::getModel('core/date')->date('d/m/Y H:i:s')) . PHP_EOL;

