<h1>Requisição inválida</h1>
<h2>Esta página espera receber o parâmetro <em>notificationCode</em> via POST.</h2>
<p>Se desejar realizar um teste de notificação, cole o notificationCode da transação e submeta novamente.</p>
<p>Para mais informações consulte <a href="https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/209089326-Configurei-o-retorno-autom%C3%A1tico-mas-parece-n%C3%A3o-funcionar-">este link</a>.</p>
<form action="" method="post">
    <input type="text" name="notificationCode" required/>
    <input type="submit" value="Enviar"/>
</form>