<?php
/** @var RicardoMartins_PagSeguro_Block_Form_Cc_CardFields $this */
$_code = $this->getPaymentMethodCode();
$_helper = $this->helper('ricardomartins_pagseguro');
?>
<li id="<?php echo $this->getElementId("total_line") ?>" data-card-index="<?php echo $this->getCardIndex() ?>" style="display: none;">
    <label for="<?php echo $this->getElementId("total") ?>" class="required"><em>*</em><?php echo $this->__('How much do You want to pay with this card?') ?></label>
    <div class="input-box">
        <input 
            type="tel" 
            id="<?php echo $this->getElementId("total") ?>" 
            name="<?php echo $this->getFieldName("total") ?>"
            value="" 
            class="input-text validate-rm-pagseguro-cc-total" 
            title="<?php echo $this->__('How much do You want to pay with this card?') ?>" 
            placeholder="0,00"
            autocomplete="off"
            data-card-index="<?php echo $this->getCardIndex() ?>"
            />
    </div>
    <div class="cc-total-progress-bar" id="<?php echo $this->getElementId("progress_bar") ?>">
        <label><?php echo $this->__('Remaining value of the payment:') ?> <span data-bind="card-metadata" data-card-field="remaining_total"></span></label>
        <span class="progress" data-role="progress"></span>
    </div>
</li>
<li data-field-profile="default" data-card-index="<?php echo $this->getCardIndex() ?>" style="display: none;">
    <label for="<?php echo $this->getElementId("number") ?>" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
    <div class="input-box">
        <input 
            type="tel" 
            id="<?php echo $this->getElementId("number") ?>" 
            name="<?php echo $this->getFieldName("number") ?>"
            value="" 
            class="input-text validate-rm-pagseguro-cc-number embedded-flag" 
            title="<?php echo $this->__('Credit Card Number') ?>" 
            maxlength="24"
            placeholder="**** **** **** ****"
            autocomplete="off"
            data-card-index="<?php echo $this->getCardIndex() ?>"
            />
        <span id="<?php echo $this->getElementId("card_brand") ?>" class="card-brand"></span>
        <input type="hidden" id="<?php echo $this->getElementId("brand") ?>" name="<?php echo $this->getFieldName("brand") ?>" />
        <input type="hidden" id="<?php echo $this->getElementId("token") ?>" name="<?php echo $this->getFieldName("token") ?>" />
    </div>
</li>
<li data-field-profile="default" data-card-index="<?php echo $this->getCardIndex() ?>" style="display: none;">
    <label for="<?php echo $this->getElementId("expiration_mth") ?>" class="required"><em>*</em><?php echo $this->__('Expiry Date') ?></label>
    <div class="input-box">
        <div class="v-fix">
            <select 
                id="<?php echo $this->getElementId("expiration_mth") ?>" 
                name="<?php echo $this->getFieldName("exp_month") ?>"
                class="month validate-cc-exp required-entry">

                <?php $_ccExpMonth = $this->getInfoData('ps_multicc_exp_month') ?>
                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>

            </select>
        </div>
        <div class="v-fix">
            <?php $_ccExpYear = $this->getInfoData('ps_multicc_exp_year') ?>
            <select 
                id="<?php echo $this->getElementId("expiration_yr") ?>" 
                name="<?php echo $this->getFieldName("exp_year") ?>" 
                class="year required-entry">

                <?php foreach ($this->getCcYears() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>

            </select>
        </div>
    </div>
</li>
<li data-field-profile="default" data-card-index="<?php echo $this->getCardIndex() ?>" style="display: none;">
    <label for="<?php echo $this->getElementId("cid") ?>" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
    <div class="input-box">
        <div class="v-fix">
            <input 
                type="tel" 
                id="<?php echo $this->getElementId("cid") ?>" 
                name="<?php echo $this->getFieldName("cid") ?>" 
                value="" 
                class="input-text cvv required-entry validate-cc-cvn validate-rm-pagseguro-cc-cid" 
                title="<?php echo $this->__('Card Verification Number') ?>" 
                maxlength="4"
                placeholder="***"
                autocomplete="off"
                data-card-index="<?php echo $this->getCardIndex() ?>"
                />
        </div>
        <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
    </div>
</li>
<li data-field-profile="default" data-card-index="<?php echo $this->getCardIndex() ?>" style="display: none;">
    <label for="<?php echo $this->getElementId("owner") ?>" class="required"><em>*</em><?php echo $this->__('Credit Card Owner\'s Name') ?></label>
    <div class="input-box">
        <input 
            type="text" 
            id="<?php echo $this->getElementId("owner") ?>" 
            name="<?php echo $this->getFieldName("owner") ?>"
            value=""
            class="input-text required-entry" 
            title="<?php echo $this->__('Credit Card Owner\'s Name') ?>" 
            autocomplete="off"
            />
    </div>
</li>
<?php if($this->isDobVisible()):?>
<li data-field-profile="default" data-card-index="<?php echo $this->getCardIndex() ?>" style="display: none;">
    <?php echo $this->getDobBlockHtml() ?>
</li>
<?php endif ?>
<?php if($this->isCpfVisible()):?>
<li data-field-profile="default" data-card-index="<?php echo $this->getCardIndex() ?>" style="display: none;">
    <label for="<?php echo $this->getElementId("owner_document") ?>" class="required"><em>*</em><?php echo $this->__('Credit Card Owner\'s CPF') ?></label>
    <div class="input-box">
        <input 
            type="tel" 
            id="<?php echo $this->getElementId("owner_document") ?>" 
            name="<?php echo $this->getFieldName("owner_document") ?>"
            value="" 
            class="input-text required-entry validate-rm-pagseguro-customer-document" 
            title="<?php echo $this->__('Credit Card Owner\'s CPF') ?>" 
            maxlength="14"
            placeholder="___.___.___-__"
            autocomplete="off"
            />
    </div>
</li>
<?php endif ?>
<li data-field-profile="default" data-card-index="<?php echo $this->getCardIndex() ?>" style="display: none;">
    <label for="<?php echo $this->getElementId("installments") ?>" class="required"><em>*</em><?php echo $this->__('Installments') ?></label>
    <div class="input-box">
        <div class="v-fix">
            <select 
                id="<?php echo $this->getElementId("installments") ?>"  
                name="<?php echo $this->getFieldName("installments") ?>"
                class="required-entry">
                
                <option value="1|<?php echo number_format($this->getGrandTotal(), 2, ".", "") ?>">1x de <?php echo $this->formatCurrency($this->getGrandTotal()) ?> sem juros</option>
                <option value="">Informe os dados do cartão para calcular as demais parcelas</option>

            </select>
        </div>
    </div>
</li>
<li id="<?php echo $this->getElementId("summary_line") ?>" data-card-index="<?php echo $this->getCardIndex() ?>" style="display: none;">
    <div id="<?php echo $this->getElementId("summary_box") ?>" class="summary-info">
        <div class="info">
            <span><strong><?php echo $this->__("card %s", $this->getCardIndex()) ?> </strong> | <span data-bind="card-metadata" data-card-field="formmated_number"></span></span>
            <span data-bind="card-metadata" data-card-field="installments_description"></span>
        </div>
        <span class="edit-link" href="#"><?php echo $this->__('edit') ?></span>
    </div>
</li>