<?php
/**
 * @package     Gamuza_Basic
 * @copyright   Copyright (c) 2016 Gamuza Technologies. (http://www.gamuza.com.br/)
 * @author      Eneias Ramos de Melo <eneias@gamuza.com.br>
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title><?php echo $this->pageTitle?></title>
<base href="<?php echo $this->getSkinUrl()?>" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="description" content="" />
<meta name="keywords" content="" />
<meta name="robots" content="*" />
<link rel="stylesheet" href="css/styles.css" type="text/css" />
<link rel="icon" href="images/favicon.png" type="image/x-icon" />
<link rel="shortcut icon" href="images/favicon.png" type="image/x-icon" />
</head>
<body>
    <div class="wrapper">
        <div class="page">
            <div class="header-container">
                <div class="header">
                    <a href="<?php echo $this->getBaseUrl()?>" title="Tolluca Store Commerce" class="logo"><img src="images/logo.png" alt="Toluca Store Commerce" /></a>
                </div>
            </div>
            <div class="main-container">
                <div class="main col1-layout">
                    <?php require_once $contentTemplate; ?>
                </div>
            </div>
            <div class="footer-container">
                <div class="footer">
                    <address class="copyright">Toluca Store&trade; is a trademark of Gamuza Technologies.<br/>Copyright &copy; 2021 Gamuza Technologies. All rights reserved.</address>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
