<?php
/**
 * @package     Gamuza_Basic
 * @copyright   Copyright (c) 2023 Gamuza Technologies (https://www.gamuza.com.br/)
 * @author      Eneias Ramos de Melo <eneias@gamuza.com.br>
 */
?>
<script type="text/javascript">
$j('a.button, button.button').removeClass('button').addClass('btn btn-success');
$j('a.checkout-button, button.btn-checkout, button.btn-cart').removeClass('checkout-button btn-checkout btn-cart').addClass('btn-lg');
$j('input.input-text').removeClass('input-text').addClass('form-control');
$j('input.checkbox:checkbox').addClass('form-check-input');
$j('input.radio:radio').addClass('form-check-input');
$j('select').addClass('form-select');
$j('textarea.input-text').removeClass('input-text').addClass('form-control');
</script>

