<?php
/**
 * @package     Gamuza_Basic
 * @copyright   Copyright (c) 2023 Gamuza Technologies (http://www.gamuza.com.br/)
 * @author      Eneias Ramos de Melo <eneias@gamuza.com.br>
 */
?>
<meta property="og:url"         content="<?php echo $this->getHomeUrl(); ?>" />
<meta property="og:title"       content="<?php echo $this->getPageTitle(); ?>" />
<meta property="og:description" content="<?php echo $this->getShortDescription(); ?>" />
<meta property="og:image"       content="<?php echo $this->getLogoUrl(); ?>" />
<meta property="og:locale"      content="<?php echo $this->getLocaleCode(); ?>" />
<meta property="og:type"        content="website" />

