<?php
/**
 * @package     Gamuza_PagCripto
 * @copyright   Copyright (c) 2022 Gamuza Technologies (http://www.gamuza.com.br/)
 * @author      Eneias Ramos de Melo <eneias@gamuza.com.br>
 */
?>
<?php
/**
 * @see Mage_Payment_Block_Info
 */
?>
<p class="subtitle"><strong><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></strong></p>

<?php if ($_specificInfo = $this->getSpecificInformation()):?>
<dl class="payment-info">
    <?php foreach ($_specificInfo as $_label => $_value):?>
        <dt><?php echo $this->escapeHtml($_label)?></dt>
        <dd><?php echo nl2br(implode("\n", $this->getValueAsArray($_value, false)))?></dd>
    <?php endforeach; ?>
</dl>
<?php endif;?>

<?php echo $this->getChildHtml()?>

