<?php
/** @var RicardoMartins_PagSeguro_Block_Form_Info_Cc $this */
?>
<?php $coreHelper = Mage::helper('core'); ?>
<strong><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?> (PagSeguro)</strong>
<?php if($info = $this->getInfo()): ?>
    <span><?php echo $this->isSandbox() ? "(Ambiente de Testes)" : ""; ?><br/>
    
    <?php if($cc1 = $this->getCc1Data()): ?>
        <?php echo $this->isMultiCcPayment() ? "<br /><strong>Cartão 1:</strong><br />" : ""; ?>
        Código da Transação: <?php echo $this->escapeHtml($this->formatTransactionId($cc1->getTransactionId()));?>
        <?php if($cc1->getTransactionId()): ?>
            <a href="<?php echo $this->getTransactionUrlOnPagSeguro($cc1->getTransactionId()) ?>" target="_blank">Ver no PagSeguro</a>
        <?php endif; ?><br/>
        <?php if($cc1->getTransactionId()): ?>
            Status da transação: <strong><?php echo $this->getTransactionStatus($cc1->getTransactionId()); ?></strong><br/>
        <?php endif; ?>
        Bandeira: <?php echo $this->escapeHtml(ucfirst($cc1->getBrand())); ?><br/>
        Últimos 4 dígitos: <?php echo $this->escapeHtml($cc1->getLast4()); ?><br/>
        Parcelas: <?php echo $this->escapeHtml($cc1->getInstallmentsQty());?>x R$ <?php echo number_format($cc1->getInstallmentsValue(), 2, ',', '.'); ?><br/>
        <?php if($gatewayData = $cc1->getGatewayData()) :?>
          <a href="javascript: void(0);" onclick="$('cc1-gatewayinfo').toggle()">Exibir/ocultar detalhes da captura/gateway</a><br/>
          <div id="cc1-gatewayinfo" style="font-size: 0.9em; display: none;">
              <?php foreach($gatewayData as $name => $value) {
                  echo $name . ': ' . $value . '<br/>';
              }?>
          </div>
        <?php endif; ?>
    <?php endif; ?>

    <?php if($this->isForceUpdateEnabled() && $cc1->getTransactionId()): ?>
        <br />
        <button
            class="scalable psupdate" 
            title="Forçar atualização" 
            onclick="if(confirm('Você tem certeza?'))setLocation('<?php echo $this->getForceUpdateUrl($cc1->getTransactionId()) ?>')" >
            <span>
                <span>Forçar atualização</span>
            </span>
        </button>
        <br />
    <?php endif;?>

    <?php if($cc2 = $this->getCc2Data()): ?>
        <?php echo $this->isMultiCcPayment() ? "<br /><strong>Cartão 2:</strong><br />" : ""; ?>
        Código da Transação: <?php echo $this->escapeHtml($this->formatTransactionId($cc2->getTransactionId()));?>
        <?php if($cc2->getTransactionId()): ?>
            <a href="<?php echo $this->getTransactionUrlOnPagSeguro($cc2->getTransactionId()) ?>" target="_blank">Ver no PagSeguro</a>
        <?php endif; ?><br/>
        <?php if($cc2->getTransactionId()): ?>
            Status da transação: <strong><?php echo $this->getTransactionStatus($cc2->getTransactionId()); ?></strong><br/>
        <?php endif; ?>
        Bandeira: <?php echo $this->escapeHtml(ucfirst($cc2->getBrand())); ?><br/>
        Últimos 4 dígitos: <?php echo $this->escapeHtml($cc2->getLast4()); ?><br/>
        Parcelas: <?php echo $this->escapeHtml($cc2->getInstallmentsQty());?>x <?php echo $coreHelper->formatCurrency($cc2->getInstallmentsValue()); ?><br/>
        <?php if($gatewayData = $cc2->getGatewayData()) :?>
            <a href="javascript: void(0);" onclick="$('cc2-gatewayinfo').toggle()">Exibir/ocultar detalhes da captura/gateway</a><br/>
            <div id="cc2-gatewayinfo" style="font-size: 0.9em; display: none;">
              <?php foreach($gatewayData as $name => $value) {
                  echo $name . ': ' . $value . '<br/>';
              }?>
          </div>
        <?php endif; ?>

        <?php if($this->isForceUpdateEnabled() && $cc1->getTransactionId()): ?>
            <br />
            <button
                class="scalable psupdate" 
                title="Forçar atualização" 
                onclick="if(confirm('Você tem certeza?'))setLocation('<?php echo $this->getForceUpdateUrl($cc2->getTransactionId()) ?>')" >
                <span>
                    <span>Forçar atualização</span>
                </span>
            </button>
        <?php endif;?>
    <?php endif; ?>

<?php endif; ?>