<?php
$_profile = $this->getProfile();
$_dataToShow = array(
        'Reference' => 'reference',
        'Código do Plano' => 'pagSeguroPlanCode',
        'Identificador' => 'tracker'
);
?>

<?php if ($_profile->getAdditionalInfo('isSandbox')) : ?>
    <strong>Transação Sandbox</strong>
<?php endif; ?>
<?php foreach ($_dataToShow as $label => $key):
    if ($value = $_profile->getAdditionalInfo($key)): ?>
        <div><?php echo $label?>: <?php echo $value;?></div>
<?php
    endif;
endforeach;
?>

<?php
if (Mage::app()->getStore()->isAdmin()) {
    if ($_profile->getId()) {
        $link = Mage::helper('adminhtml')->getUrl('adminhtml/sales_recurring_profile/view', ['profile'=> $_profile->getId()]);
    ?>
    <div>Perfil recorrente: <a href="<?php echo $link?>"><?php echo $_profile->getId();?></a></div>
    <?php
    }
    if ($codTransacao = $this->getOrder()->getExtOrderId()) {
        //@TODO linkar https://pagseguro.uol.com.br/transaction/details.jhtml?code=$codTransacao se não for sandbox
        ?>
     <div>Código da Transação: <?php echo $codTransacao; ?></div>
<?php
    }
}
