<?php
$_helper = Mage::helper('ricardomartins_pagseguro');
?>
<script type="text/javascript">
    //<![CDATA[
    var preparePagSeguro = function(){
        if(typeof RMPagSeguroObj != "undefined"){
            <?php if ($_helper->isDebugActive()): ?>
            console.info('PagSeguro was already started.');
            <?php endif; ?>
            return;
        }
        <?php if ($_helper->isDebugActive()): ?>
        console.info('PagSeguro is initiating. Wait for ready message.');
        <?php endif; ?>
        RMPagSeguroObj = new RMPagSeguro(<?php echo $_helper->getConfigJs()?>);
        console.info('PagSeguro ready');
    }
    preparePagSeguro();

    //]]>
</script>